services:
  - type: web
    name: ipo-telegram-bot
    runtime: python
    plan: free
    pythonVersion: 3.11.6
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PAN_LIST
        sync: false
      - key: PORT
        value: 10000
